// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXIa5bapR5Elz2JZoMU94ZSypft-TRspw',
    appId: '1:705923656026:web:dace9be7e1c8d329d56b63',
    messagingSenderId: '705923656026',
    projectId: 'hancode-9fe78',
    authDomain: 'hancode-9fe78.firebaseapp.com',
    storageBucket: 'hancode-9fe78.appspot.com',
    measurementId: 'G-ZK9VTY0CLT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhttsiQ1oaYStJhn2UFVRmFxa0l3x3BNg',
    appId: '1:705923656026:android:9d477eb286c44ea8d56b63',
    messagingSenderId: '705923656026',
    projectId: 'hancode-9fe78',
    storageBucket: 'hancode-9fe78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW7UZuPZ52k9gRJ0C6U-MiSsDyw2nXrvk',
    appId: '1:705923656026:ios:52f76ff29c0d50fdd56b63',
    messagingSenderId: '705923656026',
    projectId: 'hancode-9fe78',
    storageBucket: 'hancode-9fe78.appspot.com',
    iosBundleId: 'com.example.hancod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW7UZuPZ52k9gRJ0C6U-MiSsDyw2nXrvk',
    appId: '1:705923656026:ios:52f76ff29c0d50fdd56b63',
    messagingSenderId: '705923656026',
    projectId: 'hancode-9fe78',
    storageBucket: 'hancode-9fe78.appspot.com',
    iosBundleId: 'com.example.hancod',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXIa5bapR5Elz2JZoMU94ZSypft-TRspw',
    appId: '1:705923656026:web:c86571839b1b305bd56b63',
    messagingSenderId: '705923656026',
    projectId: 'hancode-9fe78',
    authDomain: 'hancode-9fe78.firebaseapp.com',
    storageBucket: 'hancode-9fe78.appspot.com',
    measurementId: 'G-53WVWS3N2J',
  );
}
