// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7K1clgwM9ZeL7ykcZsUEr4ZRsPsNXdMk',
    appId: '1:251455332928:web:a7a5858f0ae382a92ff5a5',
    messagingSenderId: '251455332928',
    projectId: 'hancode-stg',
    authDomain: 'hancode-stg.firebaseapp.com',
    storageBucket: 'hancode-stg.appspot.com',
    measurementId: 'G-H1E1BCNYN3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl8kzn7QNLug3ynJu8HLHASfKnSoq0Ibk',
    appId: '1:251455332928:android:d6f5ba7cf50c7b932ff5a5',
    messagingSenderId: '251455332928',
    projectId: 'hancode-stg',
    storageBucket: 'hancode-stg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpXoi7dmIue8hbkJyMCvvxgKYf6kRLVYs',
    appId: '1:251455332928:ios:e8ac342e6e9cf3622ff5a5',
    messagingSenderId: '251455332928',
    projectId: 'hancode-stg',
    storageBucket: 'hancode-stg.appspot.com',
    iosBundleId: 'com.example.hancod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpXoi7dmIue8hbkJyMCvvxgKYf6kRLVYs',
    appId: '1:251455332928:ios:e8ac342e6e9cf3622ff5a5',
    messagingSenderId: '251455332928',
    projectId: 'hancode-stg',
    storageBucket: 'hancode-stg.appspot.com',
    iosBundleId: 'com.example.hancod',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7K1clgwM9ZeL7ykcZsUEr4ZRsPsNXdMk',
    appId: '1:251455332928:web:1f1be96093fa94e32ff5a5',
    messagingSenderId: '251455332928',
    projectId: 'hancode-stg',
    authDomain: 'hancode-stg.firebaseapp.com',
    storageBucket: 'hancode-stg.appspot.com',
    measurementId: 'G-02PCZY7FZ8',
  );
}
